trigger: none
pool: pkdgpool
stages:
- stage: terraformdownload
  jobs:
    - job: terraform_download
      steps:
      - task: TerraformInstaller@1
        displayName: terraforminstall
        inputs:
          terraformVersion: 'latest'
- stage: terraforminit
  jobs:
    - job: terraform_init
      steps:
      - task: TerraformTask@5
        displayName: terraforminit
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/azinfra/Environment/dev'
          backendServiceArm: 'pkdgconnection'
          backendAzureRmResourceGroupName: 'pkdg_dev'
          backendAzureRmStorageAccountName: 'pkdgstorage'
          backendAzureRmContainerName: 'pkdgcontainer'
          backendAzureRmKey: 'dev.terraform.tfstate'